#
# application.yml — главный конфигурационный файл Spring Boot.
  spring:
    datasource:
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/mainDb
      username: postgres
      password: 12345

#  - Указать настройки подключения к базе данных.
#  - Указать порт приложения.
#  - Настроить параметры безопасности и JWT.
#  - Включить Swagger UI.
